spring.application.name=discord-strava-bot
spring.flyway.enabled=false
spring.jpa.open-in-view=false
server.port=${PORT:8080}
logging.structured.format.console=logstash
logging.structured.json.stacktrace.root=first
logging.structured.json.stacktrace.max-length=1200
logging.structured.json.stacktrace.max-throwable-depth=8
logging.structured.json.stacktrace.include-common-frames=false
logging.structured.json.stacktrace.include-hashes=true
